### ISSUE TITLE
Function literal

### ISSUE THREAD

**Issue by ahdinosaur** [ahdinosaur/rimu#18]
**Describe the solution you'd like**

Example:

```js
(x, y) => x + y
```

Or to within a block

```yml
$exec: (x, y) =>
  a: x + y
  b: x - y
```

**Describe alternatives you've considered or related projects**

**Additional context**
