### ISSUE TITLE
fix block operation errors

### ISSUE THREAD

**Issue by ahdinosaur** [ahdinosaur/rimu#39]
example input:

```yml
hello:
  $if: true
  world: 10
sup: "dude"
```

current error:

```yml
Compiler: Unexpected token

found end of input
```

~~i believe this is the issue: https://github.com/zesterer/chumsky/issues/397#issuecomment-1532079031~~
