### ISSUE TITLE
Stdlib: MapValues

### ISSUE THREAD

**Issue by ahdinosaur** [ahdinosaur/rimu#50]
**Describe the solution you'd like**

Example:

```
mapValues
  object:
    a: 1
    b: 2
    c: 3
  each: (value, key) =>
    value + 1
```

**TODO Checklist**

- [ ] Add to `rimu-parse`
  - [ ] Add unit test(s)
- [ ] Add to `rimu-eval`
  - [ ] Add unit test(s)
- [ ] Add spec tests
  - Use related JSON-e spec tests to start
- [ ] Add to `examples`
  - [ ] Add example to `playground`
- [ ] Add to `docs`
  - [ ] Check complete on roadmap

**Describe alternatives you've considered**
- JSON-e map over objects: https://json-e.js.org/operators.html#over-objects

**Additional context**
