### ISSUE TITLE
Stdlib: Filter

### ISSUE THREAD

**Issue by ahdinosaur** [ahdinosaur/rimu#51]
**Describe the solution you'd like**

Example:

```
filter
  list:
    - value: 10
    - value: 20
    - value: 30
  each: (item) => item.value > 15
```

**TODO Checklist**

- [ ] Add to `rimu-parse`
  - [ ] Add unit test(s)
- [ ] Add to `rimu-eval`
  - [ ] Add unit test(s)
- [ ] Add spec tests
- [ ] Add to `examples`
  - [ ] Add example to `playground`
- [ ] Add to `docs`
  - [ ] Check complete on roadmap

**Describe alternatives you've considered**

**Additional context**
